Support bytestream in Unstructured API
deepset-ai/haystack-core-integrations pull request #1082
Opened 2024-09-12 12:46 UTC by alperkaya

### Related Issues

- fixes #1075 

### Proposed Changes:

 
Unstructured API can also be called with Bytestream now in addition of Path.

### How did you test it?

Added extra unit tests

### Notes for the reviewer

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

2024-09-12 12:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/deepset-ai/haystack-core-integrations?pullRequest=1082) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/deepset-ai/haystack-core-integrations?pullRequest=1082) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/deepset-ai/haystack-core-integrations?pullRequest=1082) it.</sub>

2024-09-12 12:53 UTC, silvanocerza commented
@alperkaya can you please sign the CLA? Otherwise we can't merge this. :)

2024-09-12 12:55 UTC, alperkaya commented
> @alperkaya can you please sign the CLA? Otherwise we can't merge this. :)

done ;)

2024-09-12 13:03 UTC, silvanocerza commented on integrations/unstructured/src/haystack_integrations/components/converters/unstructured/converter.py
> +        :raises ValueError: If `meta` is a list and `sources` contains directories.
Ah, I misunderstood! That's correct.

2024-09-12 13:20 UTC, silvanocerza requested changes
This implementation has quite some problems, I would suggest taking a look at the existing converters we have in core.
https://github.com/deepset-ai/haystack/tree/main/haystack/components/converters

2024-09-13 10:15 UTC, alperkaya commented
Hi @silvanocerza,

I try to address your comment by checking the existing converters.

This version covers these cases without losing meta fields.

Case 1: Files with Meta as None
Case 2: ByteStreams with Meta as None
Case 3: Files with Meta as a Dictionary
Case 4: ByteStreams with Meta as a Dictionary
Case 5: Files with Meta as a List
Case 6: ByteStreams with Meta as a List
Case 7: Directory with Meta as a Dictionary
Case 8: Directory with Meta as a List (Should Fail)
Case 9: Combination of File Paths, ByteStreams, and Directory with Meta as a Dictionary

2024-09-16 10:26 UTC, silvanocerza commented
This is still not working as expected, I strongly suggest you copy the implementation from core.

2024-09-17 09:19 UTC, alperkaya commented
> This is still not working as expected, I strongly suggest you copy the implementation from core.

Hi, in the core repo, the solution handles either file paths or bytestreams. However, in this PR, I’m managing not just file paths and bytestreams, but also directories, where I need to fetch all files without entering subfolders. Given these additional requirements, could we explore how to modify the core solution to meet this use case, or would an alternative approach be better suited here?

2025-02-14 14:18 UTC, sjrl commented
Hey @alperkaya apologies that this has stalled for so long. I'd be happy to pick this up and help you get it over the finish line. Is this something you are still working on?

2025-05-16 11:36 UTC, closed without merging