new azure retrievers
deepset-ai/haystack-core-integrations pull request #1175
Opened 2024-11-11 23:29 UTC by ttmenezes

### Related Issues

- fixes #950 

### Proposed Changes:

 
 
This PR includes the following features:
- Implement a BM25 retriever for Azure AI Search
- Implement a hybrid search retriever for Azure AI Search

### How did you test it?

- Manual testing in Haystack pipelines
- To do: add unit tests

### Notes for the reviewer

Used the existing embedding retriever code as a template and primarily just changed the parameters in the calls to the Azure AI Search Python SDK.

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

2024-11-11 23:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/deepset-ai/haystack-core-integrations?pullRequest=1175) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/deepset-ai/haystack-core-integrations?pullRequest=1175) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/deepset-ai/haystack-core-integrations?pullRequest=1175) it.</sub>

2024-11-15 11:50 UTC, Amnah199 commented on integrations/azure_ai_search/src/haystack_integrations/components/retrievers/azure_ai_search/bm25_retriever.py
> +        filter_policy: Union[str, FilterPolicy] = FilterPolicy.REPLACE,
If we want to enable semantic ranking in all retrievers, we can add `**kwargs` here too.
```suggestion
        filter_policy: Union[str, FilterPolicy] = FilterPolicy.REPLACE,
        **kwargs,
```

2024-11-15 11:51 UTC, Amnah199 commented on integrations/azure_ai_search/src/haystack_integrations/components/retrievers/azure_ai_search/bm25_retriever.py
> +        :filter_policy: Policy to determine how filters are applied. Possible options:
```suggestion
        :filter_policy: Policy to determine how filters are applied.
        :param kwargs: Additional keyword arguments to pass to the Azure AI's search endpoint.
            Some of the supported parameters:
                - `query_type`: A string indicating the type of query to perform. Possible values are
                'simple','full' and 'semantic'.
                - `semantic_configuration_name`: The name of semantic configuration to be used when
                processing semantic queries.
```

2024-11-18 12:37 UTC, Amnah199 approved these changes
Can merge this with one more approval.

2024-11-18 14:39 UTC, julian-risch requested changes
Looks quite good to me already. I have a couple of very small change requests. Another suggestion for improvement would be to cover the run method with a unit test and mock for example _bm25_retrieval. The test could check that _bm25_retrieval is called with the expected parameters. Similarly for the hybrid retriever.

2024-11-18 16:36 UTC, ttmenezes commented on integrations/azure_ai_search/src/haystack_integrations/components/retrievers/azure_ai_search/hybrid_retriever.py
> +        :filter_policy: Policy to determine how filters are applied.
Added.

2024-11-18 16:41 UTC, ttmenezes commented on integrations/azure_ai_search/src/haystack_integrations/components/retrievers/azure_ai_search/bm25_retriever.py
> +        :filter_policy: Policy to determine how filters are applied.
Added.

2024-11-18 17:11 UTC, ttmenezes commented on integrations/azure_ai_search/src/haystack_integrations/components/retrievers/azure_ai_search/bm25_retriever.py
> +            [official Azure AI Search documentation](https://learn.microsoft.com/en-us/azure/search/).
Added.

2024-11-18 17:13 UTC, ttmenezes commented on integrations/azure_ai_search/src/haystack_integrations/components/retrievers/azure_ai_search/hybrid_retriever.py
> +            [official Azure AI Search documentation](https://learn.microsoft.com/en-us/azure/search/).
Added.

2024-11-18 17:15 UTC, ttmenezes commented on integrations/azure_ai_search/src/haystack_integrations/document_stores/azure_ai_search/document_store.py
> +        :returns: List of Document that are most similar to `query_embedding`.
Added.

2024-11-18 17:18 UTC, ttmenezes commented on integrations/azure_ai_search/src/haystack_integrations/components/retrievers/azure_ai_search/hybrid_retriever.py
> +        :param top_k: The maximum number of documents to retrieve.
Added.

2024-11-18 17:18 UTC, ttmenezes commented on integrations/azure_ai_search/src/haystack_integrations/components/retrievers/azure_ai_search/bm25_retriever.py
> +        :returns: a dictionary with the following keys:
Added.

2024-11-19 15:30 UTC, julian-risch approved these changes
Looks good to me! 👍 
Edit: I talked to @Amnah199 offline about adding unit tests for the run methods.

2024-11-20 14:08 UTC, merged