fastembed integration: add example
deepset-ai/haystack-core-integrations pull request #401
Opened 2024-02-13 07:44 UTC by nickprock

I added a simple example about the integration.

2024-02-13 09:40 UTC, masci commented
@nickprock can you run `hatch run lint:fmt` from the integration folder? That should solve the formatting issues

2024-02-13 09:42 UTC, masci requested changes

2024-02-13 09:42 UTC, masci commented on integrations/fastembed/example/example.py
> +print(result['retriever']['documents'][0])
```suggestion
print(result['retriever']['documents'][0])  # noqa: T201
```

2024-02-13 09:56 UTC, nickprock commented on integrations/fastembed/example/example.py
> +print(result['retriever']['documents'][0])
thanks @masci , done

2024-02-15 08:34 UTC, masci approved these changes
All good, sorry for the latency!

2024-02-15 08:34 UTC, merged