MongoDB Atlas: filters
deepset-ai/haystack-core-integrations pull request #542
Opened 2024-03-06 10:06 UTC by anakin87

part of #143

2024-03-06 10:10 UTC, anakin87 commented on integrations/mongodb_atlas/src/haystack_integrations/document_stores/mongodb_atlas/errors.py
> -    pass
it was unused

2024-03-06 10:18 UTC, anakin87 commented on integrations/mongodb_atlas/tests/test_document_store.py
> +class TestDocumentStore(DocumentStoreBaseTests):
I included all the base tests about filters.

2024-03-07 23:51 UTC, julian-risch requested changes
Looks very good to me already. I have one comment on a code block that we re-use multiple times. Should become a separate method for input parameter validation. The PR can be merged right after that is fixed. 👍

2024-03-08 17:03 UTC, julian-risch approved these changes
LGTM! 👍

2024-03-09 10:28 UTC, merged