Add filter_policy init parameter to all retrievers
deepset-ai/haystack-core-integrations pull request #781
Opened 2024-06-03 13:07 UTC by vblagoje

### Related Issues

- fixes #issue-number

### Proposed Changes:

 
 

### How did you test it?

### Notes for the reviewer

### Checklist

- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack-core-integrations/blob/main/CODE_OF_CONDUCT.md)
- I have updated the related issue with new insights and changes
- I added unit tests and updated the docstrings
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`.

2024-06-03 15:06 UTC, vblagoje commented
@silvanocerza we also need to address retrievers in Haystack project itself. I suppose we need to somehow coordinate this PR and that one and their releases?

2024-06-10 07:22 UTC, masci commented
Can we please break this down into single PRs for single integrations? This will make rolling out these changes with appropriate releases for the single packages easier, as well as producing better release notes.

2024-06-10 07:23 UTC, masci requested changes
Can we please break this down into single PRs for single integrations? This will make rolling out these changes with appropriate releases for the single packages easier, as well as producing better release notes.

2024-06-19 12:53 UTC, vblagoje commented
Superseded by:

https://github.com/deepset-ai/haystack-core-integrations/pull/819
https://github.com/deepset-ai/haystack-core-integrations/pull/820
https://github.com/deepset-ai/haystack-core-integrations/pull/821
https://github.com/deepset-ai/haystack-core-integrations/pull/822
https://github.com/deepset-ai/haystack-core-integrations/pull/823
https://github.com/deepset-ai/haystack-core-integrations/pull/824
https://github.com/deepset-ai/haystack-core-integrations/pull/825
https://github.com/deepset-ai/haystack-core-integrations/pull/826
https://github.com/deepset-ai/haystack-core-integrations/pull/827

2024-06-19 12:53 UTC, closed without merging