fix: `ElasticSearch` - Fallback to default filter policy when deserializing retrievers without the init parameter
deepset-ai/haystack-core-integrations pull request #898
Opened 2024-07-15 15:33 UTC by vblagoje

- fixes https://github.com/deepset-ai/haystack-core-integrations/issues/894

2024-07-15 15:34 UTC, shadeMe requested changes

2024-07-15 15:34 UTC, shadeMe commented on integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py
> +        if filter_policy := data["init_parameters"].get("filter_policy"):
Wrong file staged?

2024-07-15 15:42 UTC, vblagoje commented on integrations/chroma/src/haystack_integrations/components/retrievers/chroma/retriever.py
> +        if filter_policy := data["init_parameters"].get("filter_policy"):
Yes totally 🙏

2024-07-16 08:46 UTC, shadeMe approved these changes

2024-07-16 08:46 UTC, merged